### ISSUE TITLE
Email @ notification shows in Name option

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#100]
**WooCommerce Version** - 7.8.0
**Wordpress Version** - 6.2.2
**Plugin Version** - 1.1.6
**Description** - Email @ notification shows in Name option

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/4c35012d-cb57-4200-8373-d57293823d93)

**Comment by prince-cedcoss** [comment]
set the type "text" for name one, you have set the "mail" type  for the name.
