### ISSUE TITLE
Show error when user activate ORG plugin

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#101]
**WooCommerce Version** - 7.9.0
**Wordpress Version** - 6.2.2
**Plugin Version** - 1.1.7
**Description** - Show error when user activate ORG plugin

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/4bb9cdc4-2a44-40a9-ab65-7c4eee471f66)

**Comment by prince-cedcoss** [comment]
fixes done

**Comment by ashish-wps** [comment]
Fixed
