### ISSUE TITLE
'High-Performance order storage (COT)' issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#103]
**WooCommerce Version** - 7.9.0
**Wordpress Version** - 6.2.2
**Plugin Version** - 1.1.7
**Description** - 'High-Performance order storage (COT)' issue

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/41a38026-6dc1-403e-8ea6-62244d797241)

**Comment by prince-cedcoss** [comment]
research work and it solution was going on from dev team side , so when final solution ill get then we will update these in upcoming future update

**Comment by ashish-wps** [comment]
![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/ae021f5c-717a-4488-a119-c1380862dec5)

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/620da584-0f12-4082-940d-4158140cc710)

**Comment by prince-cedcoss** [comment]
fixed
