### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#104]
**WooCommerce Version** - 7.9.0
**Wordpress Version** - 6.2.2
**Plugin Version** - 1.1.7
**Description** - Fatal Error

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/53e45da0-5c5d-4c2e-99cd-dc30aa0f1908)

**Comment by prince-cedcoss** [comment]
the issue was not arising on my end, please use the demo site for verification

**Comment by ashish-wps** [comment]
Okay
