### ISSUE TITLE
Timing issue in Event Product 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#105]
**WooCommerce Version** - 8.0.3
**Wordpress Version** - 6.3.1
**Plugin Version** - 1.1.8
**Description** - Timing issue in Event Product 

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/160fd6c0-6487-4905-8ba3-4c8def53150f)

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/86caf86c-b609-4d12-9e2c-9a8a2d661131)

**Comment by prince-cedcoss** [comment]
issue fixed

**Comment by ashish-wps** [comment]
Fixed
