### ISSUE TITLE
Event order is not showing in Event section

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#107]
**WooCommerce Version** - 7.9.0
**Wordpress Version** - 6.2.2
**Plugin Version** - 1.1.7
**Description** - Event order is not showing in Event section

https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/79b1a4ef-83c5-445f-bc1f-3b8d8d074256

**Comment by prince-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
