### ISSUE TITLE
Decimal price issue with event product

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#108]
**WooCommerce Version** - 8.3.1
**Wordpress Version** - 6.4.1
**Plugin Version** - 1.2.2
**Description** - Decimal price issue with event product

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/8a4caea8-fae4-4ca3-a79e-5066976469b4)

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/4ad0a765-ea7c-4178-94b4-6f85de2c97e7)

**Comment by prince-cedcoss** [comment]
fixed the issue.
