### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#109]
**WooCommerce Version** - 8.3.1
**Wordpress Version** - 6.4.1
**Plugin Version** - 1.2.2
**Description** - Design issue

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/8b9b3027-8182-4555-8870-a8bd97b0dd72)

**Comment by prince-cedcoss** [comment]
this is not the issue as this depends on the theme, as we are given our own icon, that is why is shown in that way as different themes have multiple icons according to their theme. Giving compatibility to each theme is not worthy it as we are giving them our own icon.
This does not affect any functionality or CSS break.

**Comment by ashish-wps** [comment]
Okay
