### ISSUE TITLE
Barcode Feature in not working

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#110]
**WooCommerce Version - 8.5.1
Wordpress Version - 6.4.2
Plugin Version - 1.2.4
Description -** Barcode Feature in not working

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/cb8f9822-96aa-4003-8dab-5fd0d4dd9161)

**Comment by prince-cedcoss** [comment]
Just use a barcode or QR code, that is one at a time.

**Comment by ashish-wps** [comment]
Fixed
