### ISSUE TITLE
Ticket number missing when user enable Barcode feature

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#111]
**WooCommerce Version - 8.5.1
Wordpress Version - 6.4.2
Plugin Version - 1.2.4
Description -** Ticket number missing when user enable Barcode feature

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/e5050ed4-8825-4aba-bbfc-519d1568b3c7)
  

Example - 
![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/8383fab2-409f-48db-9008-d6fe44c4cc6a)

**Comment by prince-cedcoss** [comment]
The barcode maintains the ticket code's privacy as the ticket code is important for any event check-in.
So, through this barcode feature, we do not show the ticket code directly on the pdf of the event. We use barcode to save the ticket code, so you will get to see the unique ticket code on scanning this barcode.

**Comment by ashish-wps** [comment]
Okay
