### ISSUE TITLE
 Design Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#112]
**WooCommerce Version - 8.5.1
Wordpress Version - 6.4.2
Plugin Version - 1.2.4
Description -** Design Issue

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/95ecf9b2-f579-4702-a513-9d8c41d19fec)

Example -

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/d58395be-831f-467a-a383-7cc1545c717a)

**Comment by prince-cedcoss** [comment]
designed is fixes now.

**Comment by ashish-wps** [comment]
Fixed
