### ISSUE TITLE
Details missing when user place order from order again button on Thank u page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#113]
**WooCommerce Version - 8.5.1
Wordpress Version - 6.4.2
Plugin Version - 1.2.4
Description -** Details missing when user place order from order again button on Thank u page

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/d44018c6-b2a7-467f-b7d9-40f9ab0a5a8d)

**Comment by prince-cedcoss** [comment]
This is the default function of the ORDER AGAIN button, it simply adds to the cart and direct redirect to the cart page.
Our details are work when the user gets to add the product to the cart from the product page.

So, it is the bydefault functionality.

**Comment by ashish-wps** [comment]
Okay
