### ISSUE TITLE
Pro Tag should removed when user enabled pro plugin

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#114]
**WooCommerce Version - 7.3.0
Wordpress Version - 6.1.1
Plugin Version - 1.1.2
Description -** Pro Tag should removed when user enabled pro plugin

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/381985a7-8cfa-4534-990d-bafb67476fdb)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
