### ISSUE TITLE
Date should show on Event Product Page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#115]
**WooCommerce Version - 7.3.0
Wordpress Version - 6.1.1
Plugin Version - 1.1.2
Description -** Date should show on Event Product Page

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/e28c05b2-4aa5-4cf5-93aa-e86cd5636eaf)

**Comment by prince-cedcoss** [comment]
fixed now.

**Comment by pranjali-wps** [comment]
still issue pending

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/364de1c8-656a-4ea0-99de-df9326bb6be6)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
