### ISSUE TITLE
Event date format missing in ORG plugin with PRO tag

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#116]
**WooCommerce Version - 7.3.0
Wordpress Version - 6.1.1
Plugin Version - 1.1.2
Description -** Event date format missing in ORG plugin with PRO tag

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/040c4f12-bfc7-4b4c-b18e-51214ffeb6e3)

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/800dea25-1e31-436f-8235-4f3fa4a60234)

**Comment by prince-cedcoss** [comment]
fix now

**Comment by pranjali-wps** [comment]
issue fixed
