### ISSUE TITLE
Shipping cost is not add in event product 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#117]
**WooCommerce Version - 8.6.0
Wordpress Version - 6.4.3
Plugin Version - 1.2.5
Description -** Shipping cost is not add in event product 

[scrnli_19_02_2024_16-02-32.webm](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/bc2640c9-6f54-4bc1-b6ad-e55ac9e46335)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
