### ISSUE TITLE
Issue Log

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#118]
**WooCommerce Version - 8.6.0
Wordpress Version - 6.4.3
Plugin Version - 1.2.5
Description -** Issue Log

[debug.log](https://github.com/wpswings/event-tickets-manager-for-woocommerce/files/14330144/debug.log)

**Comment by prince-cedcoss** [comment]
fixed issue

**Comment by pranjali-wps** [comment]
issue fixed
