### ISSUE TITLE
The "Event PDF Body Content" is not displayed on the pdf of the ticket.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#119]
WP Version - 6.4.3
WC Version -8.6.1
Plugin version - 1.2.5
Description - The "Event PDF Body Content" is not displayed on the pdf of the ticket.

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/bed298ee-128f-478c-988c-5fb76dc3c39e)

[events71IQ93G.pdf](https://github.com/wpswings/event-tickets-manager-for-woocommerce/files/14372567/events71IQ93G.pdf)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
