### ISSUE TITLE
There should be provide the color palette for ticket Background Colour and Ticket Text Colour. 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#120]
WP Version - 6.4.3
WC Version -8.6.1
Plugin version - 1.2.5
Description - There should be provide the color palette for ticket Background Colour and Ticket Text Colour. 

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/4d362a68-b115-4764-b8c7-81cc7c301dbd)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed

**Comment by prince-cedcoss** [comment]
added now

**Comment by pranjali-wps** [comment]
issue fixed
