### ISSUE TITLE
The Ticket Background Colour and Ticket Text Colour feature is not working

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#121]
WP Version - 6.4.3
WC Version -8.6.1
Plugin version - 1.2.5
Description - The Ticket Background Colour and Ticket Text Colour feature is not working.Entered color name are not updated on downloaded ticket.

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/e09d719a-7f77-41bd-8912-3f5277d625b8)

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/383eba88-00d1-4a60-895e-f1f8a79a745b)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
