### ISSUE TITLE
The PDF Ticket template and PDF ticket preview are different

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#122]
WP Version - 6.4.3
WC Version -8.6.1
Plugin version - 1.2.5
Description - The PDF Ticket template and PDF ticket preview are different . The entered content is not displayed on the PDF Ticket Preview.

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/e365670c-2d26-452d-955a-ba5d8b5c45d7)

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/cf6ac799-e4ae-4041-805d-210429234bc9)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
