### ISSUE TITLE
The View and Add to Google Calendar buttons fluctuate on the order details page.  

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#123]
WP Version - 6.4.3
WC Version -8.6.1
Plugin version - 1.2.5
Theme - Storefront, Avada, Divi , Flatsome
Description - The View and Add to Google Calendar buttons fluctuate on the order details page.  

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/24461530-011f-4ccd-8772-393413e7dd39)

**2)In flat some theme, a warning is displayed.**
![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/cf61103c-917b-4a4e-863d-793e57a65900)

**Comment by prince-cedcoss** [comment]
fixes is done now.

**Comment by pranjali-wps** [comment]
issue fixed
