### ISSUE TITLE
plugin check issues 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#124]
WP Version - 6.4.3
WC Version -  8.7.0
Plugin version - 1.2.6 
Description - plugin check issues 

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/218482c1-6dbe-4fc2-a997-06822e5ca387)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
fixed issue
