### ISSUE TITLE
The Plugin version is not updated.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#125]
WP Version - 6.4.3
WC Version - 8.7.0
Plugin version - 1.2.6
Description - The Plugin version is not updated.

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/b38692b7-4e8f-432a-a304-2a2cf9874632)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
