### ISSUE TITLE
When I have created an event product then it is displayed a deprecated issue.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#126]
WP Version - 6.4.3
WC Version - 8.7.0
Plugin version - 1.2.6
Description - When I have created an event product then it is displayed a deprecated issue.

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/9f7fd005-27d0-4964-9385-f14faccbca93)

**Comment by prince-cedcoss** [comment]
fixednow

**Comment by pranjali-wps** [comment]
issue fixed
