### ISSUE TITLE
When I have created an event product and added a product picture then it displays an error.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#127]
WP Version - 6.4.3
WC Version - 8.7.0
Plugin version - 1.2.6
Description - When I have created an event product and added a product picture then it displays an error.
API Is not working ."WordPress Filesystem API is not available" 

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/5aeea260-a076-483e-adbb-409d93f5d9ca)

https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/dacf1204-b9db-440f-9644-b010d891d15e

**Comment by prince-cedcoss** [comment]
I have checked and no such issue I have got .
Please check and if any specific scenario was there then mention that one.

**Comment by pranjali-wps** [comment]
verified
