### ISSUE TITLE
When I activate the event ORG Plugin then it displays a "Clear" button and also it is not working. 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#129]
WP Version -6.5.0 
WC Version - 8.7.0
Plugin version - org 
Description - When I activate the event ORG Plugin then it displays a "Clear" button and also it is not working. 

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/32acdd7f-c8fe-4304-9513-fa377d8e1b45)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
