### ISSUE TITLE
When I have purchased an event product click on "Place Order" then it displays a fatal error. (GC ORG plugin is installed)

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#130]
WP Version - 6.5.3
WC Version - 8.9.0
Plugin Version - 1.2.7
Description -When I have purchased an event product click on "Proceed to checkout" then it displays a fatal error. (GC ORG plugin is installed)

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/5dc17e9f-0664-4963-92c6-9d1a65034f8d)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
still pending

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
