### ISSUE TITLE
The newly added template is not displayed in the ORG section. It is restricted to ORG users.Please modify this

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#131]
WP Version - 6.5.3
WC Version - 8.9.0
Plugin Version - 1.2.7
Description - The newly added template is not displayed in the ORG section. It is restricted to ORG users.Please modify this

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/10dc892f-f8e3-4cb1-a639-c1aab670692c)

**Comment by prince-cedcoss** [comment]
fix now

**Comment by pranjali-wps** [comment]
issue fixed
