### ISSUE TITLE
- The complete details are not displayed with **"Zenith Template"** on the event ticket.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#133]
WP Version - 6.5.3
WC Version - 8.8.3
Plugin Version - 1.2.7
Description - The complete details are not displayed with **"Zenith Template"** on the event ticket also the ticket coupon is not displayed.

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/fcf278ff-d579-4e5b-8d7b-226787c4e22b)

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/1bfbf9b1-d564-4ad7-893b-03ced4f485a5)

[events134ISC2U.pdf](https://github.com/wpswings/event-tickets-manager-for-woocommerce/files/15386370/events134ISC2U.pdf)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
