### ISSUE TITLE
If I have deleted the WooCommerce from the Backend(Woocommerce file folder) then displayed a fatal error.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#135]
WP Version - 6.5.5
WC Version - 9.0.2
Plugin Version - ORG
Description - If I have deleted the WooCommerce from the Backend(Woocommerce file folder) then displayed a fatal error.

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/11293414-8925-4f20-9f84-d7a7d746c3db)

**Comment by prince-cedcoss** [comment]
if you are deleting any woo-commerce folder, then it will show an error, as the plugin has a dependency on the woocommerce.

**Comment by pranjali-wps** [comment]
issue fixed
