### ISSUE TITLE
Theme issues-- OceanWP, 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#136]
WP Version - 6.5.5
WC Version - 9.0.2
Plugin Version - ORG
Theme issues-- OceanWP, 
Description - 
1)In Ocean WP THEME, click on the shop page then Quick view on the event product. 

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/771dbc86-bc09-4b3c-8c70-c2ef300e31e7)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
Issue fixed


![image](https://github.com/user-attachments/assets/2186052f-e076-409b-b0a7-6d615ff233d4)
