### ISSUE TITLE
plugin check issues

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#138]
WP Version - 6.5.5
WC Version - 9.0.2
Plugin Version - ORG
Description - plugin check issues

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/129398279/4c17d388-1a1a-408c-846f-888a46dd6f73)

**Comment by prince-cedcoss** [comment]
this is  query call, we can't change that but we have optimized in the code !

**Comment by pranjali-wps** [comment]
verified
