### ISSUE TITLE
Any changes are not applied to the new template.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#140]
WP Version - 6.6.1
WC Version - 9.1.4
Plugin version - 1.3.0
Description - Any changes are not applied to the new template.
1. Color changes
2. Content change
3. event details are not displayed on the event ticket.

[events111NGHEW.pdf](https://github.com/user-attachments/files/16495972/events111NGHEW.pdf)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
