### ISSUE TITLE
Event option available with enabling the plugin from General Setting 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#141]
**WP Version - 6.6.1
WC Version - 9.1.4
Plugin version - 1.3.0
Description -** Event option available with enabling the plugin from General Setting 

[scrnli_12_08_2024_17-22-43.webm](https://github.com/user-attachments/assets/ecdbf57f-766b-4828-8d89-91bb1f8e93c7)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by ashish-wps** [comment]
Fixed
