### ISSUE TITLE
User able to negative value in recurring time

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#143]
**WP Version - 6.6.1
WC Version - 9.1.4
Plugin version - 1.3.0
Description -** User able to negative value in recurring time and product edit page

![image](https://github.com/user-attachments/assets/da693d0d-551c-4b70-aabf-eaea6619e138)

![image](https://github.com/user-attachments/assets/96ecde74-adb8-42e0-b910-158f489e22b6)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by ashish-wps** [comment]
Fixed
