### ISSUE TITLE
Newly added WhatsApp integration feature should be displayed on ORG plugin with PRO tag. 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#144]
WP Version - 6.6.2
WC Version - 9.3.2
Plugin Version - ORG
Description - Newly added WhatsApp integration feature should be displayed on ORG plugin with PRO tag. 

![image](https://github.com/user-attachments/assets/3bedc10f-3082-4786-bb0e-a3c1c5a31557)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done
