### ISSUE TITLE
PHPCS ISSUE

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#145]
WP Version - 6.6.2
WC Version - 9.3.2
Plugin Version - ORG
Description - PHPCS ISSUE

[ORG_PHPcs.DOCX](https://github.com/user-attachments/files/17115144/ORG_PHPcs.DOCX)

**Comment by pradeepsinghbisht-cedcoss** [comment]
old issues

**Comment by pranjali-wps** [comment]
issue fixed
