### ISSUE TITLE
 If I have not entered any data in this, it is displayed as blank.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#147]
WP Version - 6.6.2
WC Version - 9.3.3
Plugin Version - 1.3.1
Description -  If I have not entered any data in this, it is displayed as blank.

![image](https://github.com/user-attachments/assets/4b966a85-5b86-4c3b-8b75-051715ac86ca)

![image](https://github.com/user-attachments/assets/53df88e6-e42f-44f8-9986-3d678d18b8d0)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
