### ISSUE TITLE
If I have entered the PDF BODY content, it is also displayed in the PDF Ticket Preview section.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#148]
WP Version - 6.6.2
WC Version - 9.3.3
Plugin Version - 1.3.1
Description - If I have entered the PDF BODY content, it is also displayed in the PDF Ticket Preview section.

![image](https://github.com/user-attachments/assets/4fa52982-09e5-4ccf-91ea-88d410fc3ec7)

![image](https://github.com/user-attachments/assets/e395ec7e-3025-4574-a198-789acbc19433)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by pranjali-wps** [comment]
issue fixed
