### ISSUE TITLE
After editing the ticket information the event ticket is getting an “Oops! That page can’t be found” page.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#150]
WP Version - 6.6.2
WC Version - 9.3.3
Plugin Version - 1.3.1
Description - After editing the ticket information the event ticket is getting an “Oops! That page can’t be found” page.

[scrnli_1VuNr008911h8l.webm](https://github.com/user-attachments/assets/c71940d8-c98a-44c1-b172-1e8febad1784)

![image](https://github.com/user-attachments/assets/55dab55c-28c7-493b-b1d3-d2668987cbe3)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
