### ISSUE TITLE
 I enabled the barcode from the backend, but it does not display the “vertico” template pdf ticket preview section.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#151]
WP Version - 6.6.2
WC Version - 9.3.3
Plugin Version - 1.3.1
Description -  I enabled the barcode from the backend, but by default, it does not display the “vertico” template pdf ticket preview section same as the list view of the template.

![image](https://github.com/user-attachments/assets/20f948ce-5c16-4235-ac5c-4bd3942f8d82)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed

![image](https://github.com/user-attachments/assets/7d50db06-7192-4340-8e84-79120d5fc453)
