### ISSUE TITLE
The “Vertico” template is not working properly. Content is not displayed on the downloaded event ticket pdf.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#152]
WP Version - 6.6.2
WC Version - 9.3.3
Plugin Version - 1.3.1
Description - The “Vertico” template is not working properly. Content is not displayed on the downloaded event ticket pdf.

[events170ZMMJD.pdf](https://github.com/user-attachments/files/17279458/events170ZMMJD.pdf)

**Comment by pradeepsinghbisht-cedcoss** [comment]
![image](https://github.com/user-attachments/assets/b71444b4-9e31-4197-a256-edaa6ddada49)
working

**Comment by pranjali-wps** [comment]
issue not fixed

[events113MH09S.pdf](https://github.com/user-attachments/files/17611043/events113MH09S.pdf)

**Comment by pranjali-wps** [comment]
please check again
