### ISSUE TITLE
The "Event" tag and also event ticket is not mentioned during the enable of HPOS. 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/event-tickets-manager-for-woocommerce#154]
WP Version - 6.6.2
WC Version - 9.3.3
Plugin Version - 1.3.1
Description - The "Event" tag and also event ticket is not mentioned during the enable of HPOS. 

![image](https://github.com/user-attachments/assets/ecaae23b-0187-46fb-b476-b17e26fb0b72)

![image](https://github.com/user-attachments/assets/af3ae30f-37e1-4439-9e00-fad39e54a36f)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed

![image](https://github.com/user-attachments/assets/8d86e3d2-397c-4dad-a1a3-326c730c73c9)
