### ISSUE TITLE
Events category can be created for Events type products

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [wpswings/event-tickets-manager-for-woocommerce#23]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> Products --> Events
Version: 1.0.0
Description: The Events category can be created for Events-type products.

**Comment by prince-cedcoss** [comment]
User have the  access to create the new category for event product type now.

**Comment by prince-cedcoss** [comment]
@ashish-wps  you can close this issue, as it is already implemented.

**Comment by ashish-wps** [comment]
Fixed
