### ISSUE TITLE
logo in overview page should be change

### ISSUE THREAD

**Issue by prateek-cedcoss** [wpswings/event-tickets-manager-for-woocommerce#74]
os: window11
wp: 5.9
wc: 6.1.1
version: 1.0.4
path: wpswing> overview
description: the logo in overview page image should be change.
![logo](https://user-images.githubusercontent.com/86113814/151302311-e969e8bf-b001-4027-8e6d-539d32eaeda5.png)

**Comment by prince-cedcoss** [comment]
@ashish-wps  it is fixed now , please close this.
