### ISSUE TITLE
QA Issues

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/event-tickets-manager-for-woocommerce#81]
**Bug Name -** QA Issues
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.3.1
**WordPress Version -** 5.9
**Plugin Version -** 1.0.1
**Description -**

PHPCS Issues:-

[event-tickets-manager-for-woocommerce.docx](https://github.com/wpswings/event-tickets-manager-for-woocommerce/files/8381021/event-tickets-manager-for-woocommerce.docx)

**Comment by rishabhmwb** [comment]
all the issues are resolved , some issues are left and these from libraries which is not recommended to touch

**Comment by AnuraktSachan-CEDCOSS** [comment]
If I remove lib then this issue is here.

![image](https://user-images.githubusercontent.com/76723393/163518635-72c6ef18-05ce-4dec-8e16-079fedcb8389.png)

**Comment by AnuraktSachan-CEDCOSS** [comment]
Versions are updated so please update-
Tested up to    
WC tested up to

**Comment by rishabhmwb** [comment]
all issue resolved and wc wp version updated

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
