### ISSUE TITLE
QA Issues

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/event-tickets-manager-for-woocommerce#82]
**Bug Name -** QA Issues
**Area Path -** On demo site. 
**Status -** New
**Woo Commerce Version -** 6.5.1
**WordPress Version -** 6.0.0
**Plugin Version -**
**Description -**

Change the plugin version.
event-tickets-manager-for-woocommerce.php 46

**Comment by prince-cedcoss** [comment]
issue fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
