### ISSUE TITLE
Please move "Logout" option at bottom of the list

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#88]
**WooCommerce Version** - 7.3.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 1.1.2
**Description** - Please move "Logout" option at bottom of the list

![scrnli_24_01_2023_14-31-21](https://user-images.githubusercontent.com/105413021/214252774-91067a38-a441-4edf-8580-2812a9f0236c.png)

**Comment by prince-cedcoss** [comment]
in next version

**Comment by prince-cedcoss** [comment]
@ashish-wps  this issue is fixed now, please close this.

**Comment by ashish-wps** [comment]
Fixed
