### ISSUE TITLE
Event ticket is not generated with pro plugin

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#89]
WooCommerce Version - 7.3.0
Wordpress Version - 6.1.1
Plugin Version - 1.1.2
Description - Event ticket is not generated with pro plugin

![screencapture-localhost-10013-wp-admin-post-php-2023-01-27-11_23_53](https://user-images.githubusercontent.com/105413021/215019354-85788f96-3064-4812-be4c-cf9123ca6e70.png)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
okay
