### ISSUE TITLE
Event product is not show in "My Event Tab" ( Front end ) and " Event Section" ( Back end > WooCommerce > Event )

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#90]
**WooCommerce Version** - 7.3.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 1.1.2
**Description** - Event product is not show in "My Event Tab" ( Front end ) and " Event Section" ( WooCommerce > Event back end )

![scrnli_30_01_2023_12-39-47](https://user-images.githubusercontent.com/105413021/215410720-467e9724-acc7-4584-b9bc-54df51021c8e.png)

![scrnli_30_01_2023_12-40-19](https://user-images.githubusercontent.com/105413021/215410742-c8036b6d-e673-4410-9d98-026296c1169d.png)

**Comment by prince-cedcoss** [comment]
fixed and if still this issue was there , then DM me

**Comment by ashish-wps** [comment]
Fixed
