### ISSUE TITLE
Malware Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#91]
**WooCommerce Version** - 7.3.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 1.1.2
**Description** - Malware Issue

ObfuscatedPhp /home/cedcoss/Desktop/event-tickets-manager-for-woocommerce/public/partials/wps-myevent-details-tab.php
0x21b7:$concat_with_spaces: $wps_myevent_tab_html .= '<tr><td>' . $mks['event'] . '</td><td>' . $mks['schedule'] . '</td><td>' . $mks['check_in_status'] . '</td><td>' . wc_price( $mks['price'] ) . '</td><td>' . $mks['order'] . $mks['action'] . 
0x21dd:$concat_with_spaces: $mks['event'] . '</td><td>' . $mks['schedule'] . '</td><td>' . $mks['check_in_status'] . '</td><td>' . wc_price( $mks['price'] ) . '</td><td>' . $mks['order'] . $mks['action'] . 
0x22af:$concat_with_spaces: $wps_myevent_tab_html .= '<tr><td>' . $mks['event'] . '</td><td>' . $mks['schedule'] . '</td><td>' . $mks['check_in_status'] . '</td><td>' . wc_price( $mks['price'] ) . '</td><td>' . $mks['order'] . 

ObfuscatedPhp /home/cedcoss/Desktop/event-tickets-manager-for-woocommerce/public/partials/wps-myevent-details-tab.php

**Comment by prince-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
