### ISSUE TITLE
phpcs issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#92]
**WooCommerce Version** - 7.3.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 1.1.2
**Description** - phpcs issue

[PHPcs.docx](https://github.com/wpswings/event-tickets-manager-for-woocommerce/files/10533610/PHPcs.docx)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed

[PHPcs.docx](https://github.com/wpswings/event-tickets-manager-for-woocommerce/files/10553775/PHPcs.docx)
