### ISSUE TITLE
Can't able to place to order

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#93]
**WooCommerce Version** - 7.4.1
**Wordpress Version** - 6.1.1
**Plugin Version** - 1.0.8
**Description** - Can't able to place first order

![Screenshot at 2023-03-06 12-33-06](https://user-images.githubusercontent.com/105413021/223041372-da6afee8-d374-4c2c-92ec-d9f31af3981e.png)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
