### ISSUE TITLE
Admin able enter Email or text on Image logo section.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#94]
**WooCommerce Version** - 7.4.1
**Wordpress Version** - 6.1.1
**Plugin Version** - 1.0.8
**Description** - Admin able enter Email or text on Image logo section.

![scrnli_06_03_2023_12-37-04](https://user-images.githubusercontent.com/105413021/223042275-9f4c7cde-9fe5-4288-9282-bd25e1aa503b.png)

**Comment by prince-cedcoss** [comment]
as because you don't know how the link will be , so we have allow all the possible text.

**Comment by ashish-wps** [comment]
Okay
