### ISSUE TITLE
Malware Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#96]
WooCommerce Version - 7.7.0
Wordpress Version - 6.2
Plugin Version - 1.1.5
Description - Malware Issue

https://docs.google.com/document/d/1pKAfHfPPp264WKtnzegkLVAQCLCx29uel9STRhwVJU8/edit?usp=sharing

**Comment by prince-cedcoss** [comment]
This is package file in which we cannot change or do any changes as it may lead to issue in functionality.

**Comment by ashish-wps** [comment]
Okay
