### ISSUE TITLE
Plugin version is not updated

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#97]
WooCommerce Version - 7.7.0
Wordpress Version - 6.2
Plugin Version - 1.1.5
Description - Plugin version is not updated

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/099c7752-9093-45a5-958b-d17c4d4bf872)

**Comment by prince-cedcoss** [comment]
version are updated

**Comment by ashish-wps** [comment]
Fixed
