### ISSUE TITLE
Phpcs Issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#98]
WooCommerce Version - 7.7.0
Wordpress Version - 6.2
Plugin Version - 1.1.5
Description - Phpcs Issues

[PHPcs.docx](https://github.com/wpswings/event-tickets-manager-for-woocommerce/files/11477542/PHPcs.docx)

**Comment by prince-cedcoss** [comment]
issue fixed

**Comment by ashish-wps** [comment]
Fixed
