### ISSUE TITLE
Can't Upload Default Logo

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/event-tickets-manager-for-woocommerce#99]
WooCommerce Version - 7.7.0
Wordpress Version - 6.2.1
Plugin Version - 1.1.5
Description - Can't Upload Default Logo

![image](https://github.com/wpswings/event-tickets-manager-for-woocommerce/assets/105413021/b854ee99-f9c0-4d3f-a7d2-889511e4f16f)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
